# Generated by Django 4.0.4 on 2022-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_caateory',
            new_name='variation_category',
        ),
    ]
