# Generated by Django 4.0.4 on 2022-04-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_actve',
            new_name='is_active',
        ),
    ]
